# Pizza Api

GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=tommyshado


### Get a cart
 
GET https://pizza-api.projectcodex.net/api/pizza-cart/BkL4xDXzJB/GET


### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "BkL4xDXzJB",
    "pizza_id": 8
}


### Remove a pizza from the cart

# the remove endpoint it does not remove a pizza from the cart here at the vscode but when I 
# post the remove endpoint in the js file and then use a method to to send the data into the showCartData()

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
Content-Type: application/json

{
    "cart_code": "BkL4xDXzJB",
    "pizza_id": 1,
}


### Payment for pizza

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay
Content-Type: application/json

{
    "cart_code": "BkL4xDXzJB",
    "amount": 1400,
}


 
